services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      WEBUI_PORT: 9091
    volumes:
      - "${VOLUME_PREFIX}/qbittorrent:/config"
      - "${MEDIA_PREFIX}/downloads:/downloads"
    ports:
      - 9091:9091
      - 6881:6881
      - 6881:6881/udp
    restart: "${RESTART_POLICY}"

