# Passing no environment variables since container doesn't use them
services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    container_name: prometheus
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
      # Using regular volume to have data persistency and avoid messing with
      # permissions
      - prometheus:/prometheus
    ports:
      - 9092:9090
    networks:
      - monitoring
    restart: "${RESTART_POLICY}"

volumes:
  prometheus:
networks:
  monitoring:
    name: monitoring

