services:
  rss-bridge:
    image: docker.io/rssbridge/rss-bridge:latest
    container_name: rss-bridge
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${VOLUME_PREFIX}/rss-bridge:/config"
    ports:
      - 8081:80
    restart: "${RESTART_POLICY}"

