global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        # prometheus container on this server
        - prometheus:9090

  - job_name: node
    static_configs:
      - targets:
        # node-exporter on this server
        - node-exporter:9100

