services:
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: grafana
    # Using root in container instead of custom user to have access to volume
    user: "0:0"
    environment:
      TZ: "${TZ}"
    volumes:
      - "./config/grafana.ini:/etc/grafana/grafana.ini:ro"
      - "${VOLUME_PREFIX}/grafana:/var/lib/grafana"
    ports:
      - 3030:3000
    restart: "${RESTART_POLICY}"

