services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    volumes:
      - "${VOLUME_PREFIX}/scrutiny/config:/opt/scrutiny/config"
      - "${VOLUME_PREFIX}/scrutiny/influxdb:/opt/scrutiny/influxdb"
      - "/run/udev:/run/udev:ro"
    ports:
      - 8083:8080
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
    restart: "${RESTART_POLICY}"

