version: "3"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${VOLUME_PREFIX}/jellyfin:/config"
      - "${MEDIA_PREFIX}/anime:/data/anime:ro"
      - "${MEDIA_PREFIX}/cartoons:/data/cartoons:ro"
      - "${MEDIA_PREFIX}/movies:/data/movies:ro"
      - "${MEDIA_PREFIX}/series:/data/series:ro"
    ports:
      - 8096:8096
    restart: "${RESTART_POLICY}"

