- Media:
  - Jellyfin:
      icon: jellyfin
      href: /jellyfin
      description: Media system
      server: this-server
      container: jellyfin

  - CommaFeed:
      icon: commafeed
      href: /commafeed
      description: RSS reader
      server: this-server
      container: commafeed


- Monitoring:
  - Grafana:
      icon: grafana
      href: /grafana
      description: Data analytics
      server: this-server
      container: grafana

  - Prometheus:
      icon: prometheus
      href: /prometheus
      description: Event monitoring
      server: this-server
      container: prometheus

  - Scrutiny:
      icon: scrutiny
      href: /scrutiny
      description: SMART monitoring


- Tools:
  - qBitTorrent:
      icon: qbittorrent
      href: /qbittorrent
      description: Torrent client
      server: this-server
      container: qbittorrent

  - CyberChef:
      icon: cyberchef
      href: /cyberchef
      description: Cyber Swiss Army Knife
      server: this-server
      container: cyberchef

  - Syncthing:
      icon: syncthing
      href: /syncthing
      description: File synchronization
      server: this-server
      container: syncthing

  - RSS-Bridge:
      icon: rss-bridge
      href: /rss-bridge
      description: RSS feed generator
      server: this-server
      container: rss-bridge


- Homelab:
  - Cockpit:
      icon: cockpit
      href: /cockpit
      description: Web UI for server administration

