# Style
title: Homepage
color: zinc
headerStyle: clean
statusStyle: dot

# Open links in new tabs
target: _blank


layout:
  # Services
  Media: &row-4col
    style: row
    columns: 4
  Monitoring: *row-4col
  Tools: *row-4col
  Homelab: *row-4col

  # Bookmarks
  Documentation: &col-2row
    style: column
    rows: 2
  AI: *col-2row
  Other: *col-2row

