# Style
title: Homepage
color: zinc
headerStyle: clean
statusStyle: dot

# Open links in new tabs
target: _blank


layout:
  # Services
  Media: &service-style1
    style: rows
    columns: 2
  Monitoring: *service-style1
  Tools: &service-style2
    style: row
    columns: 4

  # Bookmarks
  Documentation: &bookmark-style
    style: column
    rows: 2
  AI: *bookmark-style
  Other: *bookmark-style

