services:
  commafeed:
    image: docker.io/athou/commafeed:latest-h2
    container_name: commafeed
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${VOLUME_PREFIX}/commafeed:/commafeed/data"
    ports:
      - 8082:8082
    restart: "${RESTART_POLICY}"

